sample/hello_app/config/routes.rb
Rails.application.routes.draw do

  get 'chats/index'

 root 'toppages#index'
 
 get 'login', to: 'sessions#new'
 post 'login', to: 'sessions#create'
 delete 'logout', to: 'sessions#destroy'
 
 get 'signup', to: 'users#new'
 resources :users, only: [:index, :new, :create]

 get 'business_statues/new', to: 'business_statues#new'
 get 'business_statues/:id', to: 'business_statues#show'
 post 'business_statues', to: 'business_statues#create'
 put 'business_statues/:id', to: 'business_statues#update'
 delete 'business_statues/:id', to: 'business_statues#destroy'
 get 'business_statues', to: 'business_statues#index'
 get 'business_statues/:id/edit', to: 'business_statues#edit'
 
 resources :business_statues
 

 
 
 get '/chats', to: 'chats#index'
 resources :chats, only: [:index]

get "hello" => "hello#view" #追加
end

sample/hello_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

sample/hello_app/app/models/business_statue.rb
class BusinessStatue < ApplicationRecord
  validates :customer, presence: true, length: { maximum: 255 }
  validates :business, presence: true, length: { maximum: 255 }
  validates :date, presence: true, length: { maximum: 255 }
  validates :situation, presence: true, length: { maximum: 255 }
end

sample/hello_app/app/models/chat.rb
class Chat < ApplicationRecord
end

sample/hello_app/app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
end

sample/hello_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  def hello
    render html: "hello, world!"
  end

  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end


end

sample/hello_app/app/controllers/business_statues_controller.rb
class BusinessStatuesController < ApplicationController
 
  def index
   @nearest_date = nil
   bss = BusinessStatue.where("date IS NOT NULL AND date != ''").order(date: :asc).limit(1)
   @nearest_date = bss.first.date if bss.present?
   @business_statues = BusinessStatue.all
  case params[:sort]
  when 'situation'
   @business_statues = @business_statues.order(situation: "ASC")
  else
   @business_statues = @business_statues.order(date: "ASC")
  end
  @business_statues = @business_statues.page(params[:page]).per(10)
  end



  
  def show 
    @business_statue = BusinessStatue.find(params[:id])
  end

  def new 
    @business_statue = BusinessStatue.new
  end

  def create 
    @business_statue = BusinessStatue.new(business_statue_params)
    if @business_statue.save
      flash[:success] = 'Business_statue が正常に投稿されました'
      redirect_to business_statues_path
    else
      flash.now[:danger] = 'Business_statue が投稿されませんでした'
      render :new
    end
  end

  def edit 
    @business_statue = BusinessStatue.find(params[:id])
  end
  
  def update 
    @business_statue = BusinessStatue.find(params[:id])

    if @business_statue.update(business_statue_params)
      flash[:success] = 'Business_statue は正常に更新されました'
      redirect_to("/business_statues/#{@business_statue.id}") 
    else
      flash.now[:danger] = 'Business_statue は更新されませんでした'
      render :edit
    end
  end
  
  def destroy 
    @business_statue = BusinessStatue.find(params[:id])
    @business_statue.destroy

    flash[:success] = 'Business_statue は正常に削除されました'
    redirect_to business_statues_url
  end
  
  private

  # Strong Parameter
  def business_statue_params
    params.require(:business_statue).permit(:content, :customer, :business, :date, :situation)
  end
end

sample/hello_app/app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def index
  end
end

sample/hello_app/app/controllers/hello_controller.rb
class HelloController < ApplicationController
 def view
 @msg = 'こんにちは！'
 end
end

sample/hello_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to  controller: :toppages, action: :index
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end
  
  
  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

sample/hello_app/app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
  end
end

sample/hello_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show]
  def index
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.password = "system01"
    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      render :index
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
  
end

sample/hello_app/app/helpers/application_helper.rb
module ApplicationHelper
end

sample/hello_app/app/helpers/chats_helper.rb
module ChatsHelper
end

sample/hello_app/app/helpers/session_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

sample/hello_app/app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

sample/hello_app/app/helpers/users_helper.rb
module UsersHelper
end

sample/hello_app/app/views/business_statues/_form.html.erb
<div class="row">
  <div class="col-6">
    <%= form_with(model: business_statue, local: true) do |f| %>
      <% if business_statue.errors.any? %>
        <div id="error_explanation" class="alert alert-warning">
          <ul class="mb-0">
            <% business_statue.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label :customer, '会社名' %>
        <%= f.text_field :customer, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :business, '業務内容' %>
        <%= f.text_field :business, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :date, '処理期限日' %>
        <%= f.date_field :date, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :situation, '状況' %>
        <%= f.select :situation, {'未着手': '1.未着手', '作成済': '2.作成済', '提出済': '3.提出済'}, { include_blank: '選択してください'}, { class: 'form-control' , required: true } %>
      </div>
      <div class="form-group">
        <%= f.submit '登録', class: 'btn btn-primary btn-block' %>
      </div>
    <% end %>
  </div>
</div>

<%= link_to '業務内容・状況一覧に戻る', "/business_statues", class: "btn btn-primary" %>

sample/hello_app/app/views/business_statues/edit.html.erb
<h1>id: <%= @business_statue.id %> の業務内容・状況 編集</h1>

<%= render 'form', business_statue: @business_statue %>

<%= link_to '業務内容・状況 詳細に戻る', "/business_statues/#{@business_statue.id}", class: "btn btn-light" %> 

sample/hello_app/app/views/business_statues/index.html.erb
<h2>業務内容・状況一覧</h2>
<%= link_to '処理期限日順', business_statues_path(sort: :date), class: "btn btn-primary" %>
<%= link_to '状況順', business_statues_path(sort: :situation), class: "btn btn-primary" %>


<% if @business_statues.any? %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>id</th>
        <th>会社名</th>
        <th>業務内容</th>
        <th>処理期限日</th>
        <th>状況</th>
      </tr>
    </thead>
    <tbody>
      <% @business_statues.each do |business_statue| %>
        <tr>
          <td><%= link_to "#{business_statue.id}", "/business_statues/#{business_statue.id}" %></td>
          <td><%= business_statue.customer %></td>
          <td><%= business_statue.business %></td>
          <% if @nearest_date == business_statue.date %>
            <td style="background: red;"><%= business_statue.date %></td>
          <% else %>
            <td><%= business_statue.date %></td>
          <% end %>
          <%- if business_statue.situation.to_s.include?('1.未着手') %>
                <td style="background: red;"><%= business_statue.situation %></td>
          <% else %>
                <td><%= business_statue.situation %></td>
          <% end %>


          
        </tr>
      <% end %>
    </tbody>
  </table>
  <div>
    <%= paginate @business_statues %>
  </div>
<% end %>

<%= link_to '業務内容・状況　新規登録', business_statues_new_path, class: "btn btn-primary" %>

sample/hello_app/app/views/business_statues/new.html.erb
<h1>業務内容・状況 新規登録</h1>

<%= render 'form', business_statue: @business_statue %>

sample/hello_app/app/views/business_statues/show.html.erb
<h3>id: <%= @business_statue.id %> の業務内容・状況 詳細</h3>

<table class="table table-bordered">
  <tr>
    <th>id</th>
    <td><%= @business_statue.id %></td>
  </tr>
  <tr>
    <th>会社名</th>
    <td><%= @business_statue.customer %></td>
  </tr>
  <tr>
    <th>業務内容</th>
    <td><%= @business_statue.business %></td>
  </tr>
  <tr>
    <th>処理期限日</th>
    <td><%= @business_statue.date %></td>
  </tr>
  <tr>
    <th>状況</th>
    <td><%= @business_statue.situation %></td>
  </tr>
</table>

<%= link_to 'この業務内容・状況を編集する', "/business_statues/#{@business_statue.id}/edit", class: 'btn btn-light' %>
<%= link_to 'この業務内容・状況を削除する', "/business_statues/#{@business_statue.id}", method: :delete, data: { confirm: '本当に削除してよろしいですか？' }, class: 'btn btn-danger' %>
<%= link_to '業務内容・状況一覧に戻る', business_statues_path, class: "btn btn-primary" %>

sample/hello_app/app/views/chats/index.html.erb
<!DOCTYPE html>
<html lang="ja">

<head>
  <meta charset="utf-8">
  <title>Realtime Chat</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

  <!-- Font Awesomeのアイコンフォント -->
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

  <!-- 自サイトのCSS -->
  <link rel="stylesheet" href="css/main.css">
</head>

<body>
  <div class="message-template">
    <!-- 受信メッセージのテンプレート -->
    <div class="message message--received">
      <div class="message__profile">
        <img class="message__user-image" src="img/default-profile-image.png" width="46" height="46" alt="プロフィール画像">
      </div>
      <div class="message__body">
        <div class="message__user-name"></div>
        <div class="message__text"></div>
        <div class="message__info">
          <span class="message__time"></span>
        </div>
      </div>
    </div>
    <!-- /.message -->

    <!-- 送信メッセージのテンプレート -->
    <div class="message message--sent">
      <div class="message__profile">
        <a href="#settingsModal" data-toggle="modal"><img class="message__user-image"
            src="img/default-profile-image.png" width="46" height="46" alt="プロフィール画像"></a>
      </div>
      <div class="message__body">
        <div class="message__user-name"></div>
        <div class="message__text"></div>
        <div class="message__info">
          <span class="message__time"></span>
        </div>
      </div>
    </div>
    <!-- /.message -->
  </div>

  <!-- ルーム作成モーダル -->
  <div id="createRoomModal" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <form id="create-room-form">
          <div class="modal-header">
            <h4 class="modal-title">ルーム作成</h4>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <div id="create-room__room-name" class="form-group">
              <label for="room-name" class="col-form-label">ルーム名を入力してください</label>
              <input id="room-name" type="text" class="form-control" required>
            </div>
            <div id="create-room__help" class="alert alert-danger"></div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">
              キャンセル
            </button>
            <button type="submit" class="btn btn-primary">作成</button>
          </div>
        </form>
      </div>
      <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
  </div>
  <!-- /#createRoomModal -->

  <!-- ルーム削除モーダル -->
  <div id="deleteRoomModal" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title">ルーム削除</h4>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <span id="delete-room__name"></span> を削除しますか？<br>
          ルーム内のすべてのメッセージも削除されます。
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">
            キャンセル
          </button>
          <button id="delete-room__button" type="button" class="btn btn-danger">
            削除
          </button>
        </div>
      </div>
      <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
  </div>
  <!-- /#deleteRoomModal -->

  <!-- ユーザ情報設定モーダル -->
  <div id="settingsModal" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content">
        <div class="modal-header mx-3">
          <h4 class="modal-title">設定</h4>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body mx-3 mt-3">
          <form id="settings-form">
            <div class="form-group row">
              <label for="settings-nickname" class="col-lg-3 col-form-label">ニックネーム</label>
              <div class="col-lg-9">
                <input id="settings-nickname" type="text" class="form-control" required>
              </div>
            </div>
            <div class="form-group row">
              <div class="col-lg-3">
                プロフィール画像
              </div>
              <div class="col-lg-7 mb-2 mb-lg-0">
                <div class="custom-file">
                  <input id="settings-profile-image" type="file"
                    accept=".jpg,.jpeg,.png,.gif, image/jpeg,image/png,image/gif" class="custom-file-input">
                  <label id="settings-profile-image-label" class="custom-file-label"
                    for="settings-profile-image">ファイルを選択</label>
                </div>
              </div>
              <div class="col-lg-2">
                <label for="settings-profile-image">
                  <img id="settings-profile-image-preview" src="img/default-profile-image.png" width="46" height="46"
                    alt="プロフィール画像">
                </label>
                <div id="settings-profile-image-loading-container">
                  <i class="settings-profile-image-loading-icon fa fa-refresh" aria-hidden="true"></i>
                </div>
              </div>
            </div>
          </form>
        </div>
      </div>
      <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
  </div>
  <!-- /#settingsModal -->

  <!-- 最初のローディング表示 -->
  <section id="loading" class="view">
    <i class="initial-loading-icon fa fa-refresh" aria-hidden="true"></i>
  </section>
  <!-- /#loading -->

  <!-- ログイン画面 -->
  <section id="login" class="view">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-sm-10 col-md-8 col-lg-6">
          <form id="login-form">
            <div id="login__email" class="form-group">
              <label for="login-email" class="col-form-label">
                メールアドレス
              </label>
              <div>
                <input id="login-email" type="email" class="form-control" required>
              </div>
            </div>
            <div id="login__password" class="form-group">
              <label for="login-password" class="col-form-label">
                パスワード
              </label>
              <div>
                <input id="login-password" type="password" class="form-control" required>
                <p class="form-text text-muted">
                  初めての方は、登録するパスワードを入力してください
                </p>
              </div>
            </div>

            <div id="login__help" class="alert alert-danger"></div>
            <div class="form-group login__submit">
              <div>
                <button id="login__submit-button" type="submit" class="btn btn-primary">
                  ログイン
                </button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </section>
  <!-- /#login -->

  <!-- チャット画面 -->
  <section id="chat" class="view">

    <!-- ナビゲーションバー -->
    <nav class="navbar fixed-top navbar-expand-md navbar-light bg-light py-md-1">
      <div class="container">

        <!-- ホームリンク -->
        <a href="./index.html" class="navbar-text" aria-label="ホーム">
          <i class="fa fa-home fa-lg"></i>
        </a>

        <!-- 画面幅が狭い時に表示されるハンバーガーメニュー -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div id="navbarSupportedContent" class="collapse navbar-collapse">
          <div class="navbar-nav mr-auto">
            <div class="nav-item dropdown ml-md-3">
              <a id="navbarDropdown" class="nav-link dropdown-toggle room-list-menu" href="#" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                ルーム
              </a>
              <div id="room-list" class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a href="#createRoomModal" class="dropdown-item craete-room-link" data-toggle="modal">新しいルームを作成</a>
                <a id="delete-room-menuitem" href="#deleteRoomModal" class="dropdown-item"
                  data-toggle="modal">現在のルームを削除</a>
                <div role="separator" class="dropdown-divider"></div>
              </div>
            </div>
          </div>
          <div class="navbar-nav dropdown">
            <div class="nav-item">
              <a href="#" id="navbarRightDropdown" class="nav-link dropdown-toggle menu-profile py-0"
                data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                <span id="menu-profile-name" class="mr-2"></span>
                <img id="menu-profile-image" src="img/default-profile-image.png" width="46" height="46" alt="プロフィール画像">
              </a>
              <div class="dropdown-menu dropdown-menu-md-right" aria-labelledby="navbarRightDropdown">
                <a class="dropdown-item room-settings-link" data-toggle="modal" href="#settingsModal">
                  設定
                </a>
                <div role="separator" class="dropdown-divider"></div>
                <a id="logout__link" href="#" class="dropdown-item">ログアウト</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </nav>

    <!-- メッセージ表示部 -->
    <div id="message-list" class="clearfix"></div>

    <!-- メッセージ投稿フォーム -->
    <form id="comment-form">
      <div class="input-group">
        <input id="comment-form__text" type="text" class="form-control form-control-lg">
        <span class="input-group-append">
          <button type="submit" class="btn btn-lg btn-secondary comment-form__submit" aria-label="送信">
            <i class="fa fa-paper-plane" aria-hidden="true"></i>
          </button>
        </span>
      </div>
      <!-- /.input-group -->
    </form>
    <!-- /#comment-form -->
    
  </section>
  <!-- /#chat -->

  <!-- Firebaseのセットアップコード（下記のSDKのバージョンは6.2.0） -->
  <!-- The core Firebase JS SDK is always required and must be listed first 
    (中心となるFirebase SDKです。常に必要で、最初に記述する必要があります) -->
  <script src="https://www.gstatic.com/firebasejs/6.2.0/firebase-app.js"></script>

  <!-- TODO: Add SDKs for Firebase products that you want to use
     https://firebase.google.com/docs/web/setup#config-web-app 
    (使いたいFirebaseサービス用のSDKを加えます) -->
  <script src="https://www.gstatic.com/firebasejs/6.2.0/firebase-auth.js"></script>
  <script src="https://www.gstatic.com/firebasejs/6.2.0/firebase-database.js"></script>
  <script src="https://www.gstatic.com/firebasejs/6.2.0/firebase-storage.js"></script>

  <script>
    // Your web app's Firebase configuration
    const firebaseConfig = {
      apiKey: "AIzaSyBWlOqRwMu-E34hhe-UA0-NjKU5Ny3q2Bs",
      authDomain: "realtime-chat-9a6ba.firebaseapp.com",
      databaseURL: "https://realtime-chat-9a6ba.firebaseio.com",
      projectId: 'realtime-chat-9a6ba',
      storageBucket: "realtime-chat-9a6ba.appspot.com",
    };
    // Initialize Firebase
    firebase.initializeApp(firebaseConfig);
  </script>

  <!-- jQuery -->
  <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>

  <!-- Popper.js, 次に Bootstrap JS -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

  <!-- 外部ライブラリ -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js"></script>

  <!-- 自サイトのJavaScript -->
  <script src="js/main.js"></script>
</body>

</html>

sample/hello_app/app/views/hello/view.html.erb
<div id=“main”>
<%= @msg %>
</div>

sample/hello_app/app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

sample/hello_app/app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

sample/hello_app/app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <a class="navbar-brand" href="/">Business management system</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <% if logged_in? %>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Users <%=current_user.name %></a>
            
            <ul class="dropdown-menu dropdown-menu-right">
              <li class="dropdown-item"><%= link_to 'Logout', logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item"><%= link_to 'Signup', signup_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'Login', login_path, class: 'nav-link' %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

sample/hello_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html  lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Business management system</title>
    <%= csrf_meta_tags %>
    

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
  </body>
</html>

sample/hello_app/app/views/toppages/index.html.erb
<% if logged_in? %>
  <div id="main">
          <section id="List">
              <h2>業務管理システム一覧</h2>
              <ul>
                  <p>
                     <%= link_to '業務内容・状況一覧', 'business_statues', class: "btn btn-primary" %>
                  </p>
                  <p>
                    <%= link_to "業務報告システム", "https://f9d2fcc466b64f0cb889988b55759b37.vfs.cloud9.us-east-1.amazonaws.com/_static/realtime-chat/index.html", class: "btn btn-primary" %>
                  </p>
              </ul>
          </section>
  </div>
<% else %>
  <div class="center jumbotron">
    <div class="text-center">
      <h1>Welcome to the Business management system</h1>
      <%= link_to 'Sign up now!', signup_path, class: 'btn btn-lg btn-primary' %>
    </div>
  </div>
<% end %>

sample/hello_app/app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

sample/hello_app/app/views/users/index.html.erb
<div class="center jumbotron">
  <div class="text-center">
    <h1>ユーザ登録完了致しました</h1>
    <%= link_to 'ここからログインして下さい', login_path, class: 'btn btn-lg btn-primary' %>
  </div>
</div>

sample/hello_app/app/views/users/new.html.erb
<div class="text-center">
  <h1>Sign up</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      
      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit 'Sign up', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>